// <auto-generated />
using System;
using BookShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407001257_AddStockToBooks")]
    partial class AddStockToBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mikhail Bulgakov",
                            Description = "A novel about good and evil, love and betrayal.",
                            Genre = "Classic",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8739161-L.jpg",
                            Price = 12m,
                            Stock = 10,
                            Title = "The Master and Margarita"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Description = "A classic of the dystopian genre.",
                            Genre = "Dystopia",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8575708-L.jpg",
                            Price = 10m,
                            Stock = 8,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Fyodor Dostoevsky",
                            Description = "A psychological novel about moral choice.",
                            Genre = "Classic",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8739161-L.jpg",
                            Price = 9m,
                            Stock = 5,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.K. Rowling",
                            Description = "The first book about a young wizard.",
                            Genre = "Fantasy",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8234665-L.jpg",
                            Price = 14m,
                            Stock = 15,
                            Title = "Harry Potter and the Philosopher Stone"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert Martin",
                            Description = "A guide to writing good clean code.",
                            Genre = "Programming",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8576065-L.jpg",
                            Price = 22m,
                            Stock = 6,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            Description = "A fantasy novel about the journey of Bilbo Baggins.",
                            Genre = "Fantasy",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8406786-L.jpg",
                            Price = 13m,
                            Stock = 12,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 7,
                            Author = "F. Scott Fitzgerald",
                            Description = "A story of wealth, love and the American Dream.",
                            Genre = "Classic",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8432938-L.jpg",
                            Price = 8m,
                            Stock = 7,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Frank Herbert",
                            Description = "An epic science fiction saga set in a desert world.",
                            Genre = "Sci-Fi",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8786077-L.jpg",
                            Price = 15m,
                            Stock = 9,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Paulo Coelho",
                            Description = "A philosophical novel about following your dreams.",
                            Genre = "Fiction",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8215523-L.jpg",
                            Price = 11m,
                            Stock = 14,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Aldous Huxley",
                            Description = "A dystopian vision of a future controlled society.",
                            Genre = "Dystopia",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8739166-L.jpg",
                            Price = 10m,
                            Stock = 6,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Andrew Hunt",
                            Description = "Essential advice for software developers.",
                            Genre = "Programming",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8576066-L.jpg",
                            Price = 25m,
                            Stock = 4,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Harper Lee",
                            Description = "A story of racial injustice and moral growth.",
                            Genre = "Classic",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8576067-L.jpg",
                            Price = 9m,
                            Stock = 11,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 13,
                            Author = "J.R.R. Tolkien",
                            Description = "An epic quest to destroy the One Ring.",
                            Genre = "Fantasy",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8406787-L.jpg",
                            Price = 20m,
                            Stock = 8,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Ray Bradbury",
                            Description = "A world where books are banned and burned.",
                            Genre = "Dystopia",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8739167-L.jpg",
                            Price = 9m,
                            Stock = 7,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Douglas Adams",
                            Description = "A hilarious sci-fi comedy about the end of the world.",
                            Genre = "Sci-Fi",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8576068-L.jpg",
                            Price = 11m,
                            Stock = 10,
                            Title = "The Hitchhiker Guide to the Galaxy"
                        });
                });

            modelBuilder.Entity("BookShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookShop.Models.CartItem", b =>
                {
                    b.HasOne("BookShop.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
